name:eRNASeq
channels:!!python/tuple
 - !!python/unicode 
   'bioconda'
 - !!python/unicode
   'r'
 - !!python/unicode
   'defaults'
dependencies:
 - python=3.6
 - bioconda::snakemake=5.1.3=py36_0
 - bioconda::fastqc=0.11.5=1
 - bioconda::fastx_toolkit=0.0.14=2
 - bioconda::multiqc=0.8=py35_0
 - bioconda::java-jdk=8.0.92=1
 - bioconda::novoalign=3.07.00=3
 - bioconda::tophat=2.1.1=2
 - bioconda::hisat2=2.0.5=2
 - bioconda::star=2.6.0b=2
 - bioconda::gmap=2018.03.25=0
 - bioconda::mapsplice=2.2.0=2
 - bioconda::subread=1.6.1=2
 - bioconda::soapsplice=1.10=2
 - bioconda::cufflinks=2.2.1=2
 - bioconda::stringtie=1.3.3=2
 - bioconda::kallisto=0.44.0=0
 - bioconda::salmon=0.9.1=1
 - bioconda::sailfish=0.10.1=0
 - bioconda::express=0.5.1=0
 - bioconda::rsem=1.3.0=1
 - bioconda::qualimap=2.2=0
 - bioconda::bamtools=2.4.0=3
 - bioconda::bcftools=1.5=0
 - bioconda::bedops=2.4.26=0
 - bioconda::bedtools=2.26.0=0
 - bioconda::pybedtools=0.7.8=py35_1
 - bioconda::pysam=0.9.0=py35_1
 - bioconda::picard=2.7.1=py35_0
 - bioconda::bioconductor-annotate=1.50.0=r3.3.1_1
 - bioconda::bioconductor-annotationdbi=1.36.0=r3.3.1_1
 - bioconda::bioconductor-biobase=2.32.0=0
 - bioconda::bioconductor-biocgenerics=0.20.0=r3.3.1_0
 - bioconda::bioconductor-biocparallel=1.6.6=r3.3.1_0
 - bioconda::bioconductor-biomart=2.28.0=r3.3.1_0
 - bioconda::bioconductor-biostrings=2.40.0=r3.3.1_0
 - bioconda::bioconductor-deseq2=1.12.4=r3.3.1_3
 - bioconda::bioconductor-edger=3.14.0=r3.3.1_1
 - bioconda::bioconductor-genefilter=1.54.2=r3.3.1_0
 - bioconda::bioconductor-geneplotter=1.50.0=r3.3.1_0
 - bioconda::bioconductor-genomeinfodb=1.8.7=r3.3.1_0
 - bioconda::bioconductor-genomicalignments=1.10.0=r3.3.1_0
 - bioconda::bioconductor-genomicfeatures=1.26.0=r3.3.1_2
 - bioconda::bioconductor-genomicranges=1.26.1=r3.3.1_1
 - bioconda::bioconductor-iranges=2.8.0=r3.3.1_0
 - bioconda::bioconductor-limma=3.29.0=r3.3.1_0
 - bioconda::bioconductor-rsamtools=1.26.1=r3.3.1_0
 - bioconda::bioconductor-rtracklayer=1.34.1=r3.3.1_0
 - bioconda::bioconductor-s4vectors=0.12.0=r3.3.1_0
 - bioconda::bioconductor-summarizedexperiment=1.4.0=r3.3.1_0
 - bioconda::bioconductor-tximport=1.0.3=r3.3.1_0
 - bioconda::bioconductor-xvector=0.12.1=r3.3.1_0
 - bioconda::bioconductor-zlibbioc=1.18.0=r3.3.1_0
 - bioconda::htslib=1.3.2=0
 - bioconda::intervaltree=2.1.0=py35_0
 - bioconda::r-ggplot2=2.1.0=r3.3.1_0
 - bioconda::r-pheatmap=1.0.8=r3.3.1_0
 - bioconda::r-readr=0.2.2=r3.3.1_0
